name: flutter_media_player
description: A Flutter-based media player for Windows powered by a Rust core engine.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
